import { PrismaClient } from '@prisma/client';

// Keep this 100% empty. No objects, no strings.
const prisma = new PrismaClient();

async function main() {
  console.log('--- Starting Seed Script ---');
  console.log('--- Deleting existing news data ---');
  await prisma.post.deleteMany({});
  console.log('--- Deleting existing news data ---');
  await prisma.post.deleteMany({});

  const newsData = [
    {
      title: 'Punjab Announces New Teacher Recruitment Drive',
      slug: 'punjab-teacher-recruitment-2026',
      category: 'Education',
      image: 'punjab-education.jpg',
      date: new Date('2026-01-09T09:30:00Z'),
      published: true,
      excerpt: 'The Punjab government has announced a large-scale recruitment drive to address teacher shortages in public schools.',
      content: 'By our Correspondent, Lahore, The Punjab government on Wednesday announced a new recruitment drive aimed at hiring over 15,000 teachers for public sector schools across the province. Officials said the move is intended to address long-standing staff shortages, particularly in rural districts. According to the School Education Department, recruitment will be merit-based and conducted through a centralized testing system. Authorities added that priority will be given to science and mathematics teachers to improve learning outcomes.',
    },
    {
      title: 'HEC Revises Undergraduate Curriculum Nationwide',
      slug: 'hec-revises-undergraduate-curriculum',
      category: 'Education',
      image: 'hec-campus.jpg',
      date: new Date('2026-01-08T11:00:00Z'),
      published: true,
      excerpt: 'The Higher Education Commission has approved revisions to undergraduate curricula across Pakistani universities.',
      content: 'By Staff Reporter, Islamabad, The Higher Education Commission (HEC) has approved comprehensive revisions to undergraduate curricula in public and private universities. The changes aim to align academic programs with modern industry requirements. Officials stated that new courses on digital skills, critical thinking, and research methodology will be introduced from the next academic session. Universities have been directed to implement the updated framework by Fall 2026.',
    },
    {
      title: 'Sindh Launches School Meal Program',
      slug: 'sindh-school-meal-program',
      category: 'Education',
      image: 'school-meals.jpg',
      date: new Date('2026-01-07T10:15:00Z'),
      published: true,
      excerpt: 'The Sindh government has launched a school meal program to tackle malnutrition among students.',
      content: 'By our Correspondent, Karachi, The Sindh government has initiated a school meal program in government schools located in underprivileged areas. The program aims to improve student attendance and combat child malnutrition. Education officials said the meals will include milk, eggs, and fortified snacks. The initiative is being rolled out in phases and will initially cover primary schools in Karachi and interior Sindh.',
    },
    {
      title: 'KP Introduces Digital Attendance System in Colleges',
      slug: 'kp-digital-attendance-colleges',
      category: 'Education',
      image: 'digital-attendance.jpg',
      date: new Date('2026-01-06T14:20:00Z'),
      published: true,
      excerpt: 'Khyber Pakhtunkhwa has introduced a digital attendance system in public colleges.',
      content: 'By Staff Reporter, Peshawar, The Khyber Pakhtunkhwa Higher Education Department has launched a biometric attendance system for teachers and students in public colleges. The move aims to ensure transparency and reduce absenteeism. Officials stated that the system will be linked to a centralized database. Training sessions for staff are currently underway before full implementation.',
    },
    {
      title: 'PCB Announces Squad for T20 Series',
      slug: 'pcb-t20-squad-announcement',
      category: 'Cricket',
      image: 'pcb-t20.jpg',
      date: new Date('2026-01-09T12:00:00Z'),
      published: true,
      excerpt: 'Pakistan Cricket Board announced the squad for the upcoming T20 series on Tuesday.',
      content: 'By our Correspondent, Lahore, The Pakistan Cricket Board announced the national squad for the upcoming T20 series, placing a strong emphasis on youth. Several emerging players have been included as part of the board’s long-term strategy. PCB officials said the series will allow young cricketers to gain international exposure. Senior players have also been retained to provide balance and mentorship.',
    },
    {
      title: 'National Stadium Karachi Set for Renovation',
      slug: 'national-stadium-renovation',
      category: 'Cricket',
      image: 'national-stadium.jpg',
      date: new Date('2026-01-08T16:45:00Z'),
      published: true,
      excerpt: 'PCB has approved renovation plans for the National Stadium Karachi.',
      content: 'By Staff Reporter, Karachi, The Pakistan Cricket Board has approved major renovation work at the National Stadium in Karachi. The project includes seating upgrades, improved lighting, and modern player facilities. Officials said the renovations aim to meet international standards ahead of future ICC events. Construction is expected to be completed within nine months.',
    },
    {
      title: 'PSL 11 Draft Scheduled in Islamabad',
      slug: 'psl-11-draft-islamabad',
      category: 'Cricket',
      image: 'psl-draft.jpg',
      date: new Date('2026-01-07T18:00:00Z'),
      published: true,
      excerpt: 'Pakistan Super League season 11 draft will be held in Islamabad next month.',
      content: 'By Sports Desk, Islamabad, The Pakistan Cricket Board has announced that the PSL 11 players’ draft will take place in Islamabad. Franchise representatives are expected to participate in person. Officials said the event will be broadcast live and will include new player categories. PSL management expects strong international participation.',
    },
    {
      title: 'Former Captain Appointed as Batting Consultant',
      slug: 'former-captain-batting-consultant',
      category: 'Cricket',
      image: 'batting-consultant.jpg',
      date: new Date('2026-01-06T13:10:00Z'),
      published: true,
      excerpt: 'PCB has appointed a former national captain as batting consultant for the team.',
      content: 'By Staff Reporter, Lahore, The Pakistan Cricket Board has appointed a former national captain as the batting consultant for the national side. The appointment is part of efforts to strengthen the team’s performance. PCB officials said the consultant will work closely with players during training camps and international tours.',
    },
    {
      title: 'Pakistan Records Growth in Textile Exports',
      slug: 'pakistan-textile-exports-growth',
      category: 'Business',
      image: 'textile-exports.jpg',
      date: new Date('2026-01-09T10:00:00Z'),
      published: true,
      excerpt: 'Pakistan’s textile exports have recorded a notable increase during the first half of the fiscal year.',
      content: 'By our Correspondent, Karachi, Pakistan’s textile exports recorded a steady increase during the first six months of the current fiscal year, according to data released by the Ministry of Commerce. Officials attributed the growth to improved energy supply and stable international demand. Industry representatives said government incentives and reduced power tariffs helped manufacturers enhance production. However, exporters emphasized the need for long-term policy consistency to maintain momentum.',
    },
    {
      title: 'SBP Keeps Policy Rate Unchanged',
      slug: 'sbp-policy-rate-unchanged',
      category: 'Business',
      image: 'sbp-policy.jpg',
      date: new Date('2026-01-08T14:30:00Z'),
      published: true,
      excerpt: 'State Bank of Pakistan has decided to keep the policy rate unchanged in its latest review.',
      content: 'By Staff Reporter, Islamabad, The State Bank of Pakistan (SBP) on Monday announced its decision to maintain the current policy rate, citing easing inflationary pressures. The decision came after a meeting of the Monetary Policy Committee. SBP officials stated that while inflation is showing signs of moderation, risks related to global commodity prices still persist. Market analysts described the move as supportive of economic stability.',
    },
    {
      title: 'New IT Park Approved for Lahore',
      slug: 'it-park-lahore-approved',
      category: 'Business',
      image: 'it-park.jpg',
      date: new Date('2026-01-07T11:45:00Z'),
      published: true,
      excerpt: 'The Federal government has approved the establishment of a new IT park in Lahore.',
      content: 'By our Correspondent, Lahore, The federal government has approved a new state-of-the-art IT park in Lahore aimed at boosting Pakistan’s technology sector. The project will be developed in collaboration with the private sector. Officials said the IT park will provide facilities for startups, software houses, and foreign investors. The initiative is expected to create thousands of jobs for skilled youth.',
    },
    {
      title: 'Pakistan Stock Exchange Ends Week on Positive Note',
      slug: 'psx-weekly-gains',
      category: 'Business',
      image: 'psx-market.jpg',
      date: new Date('2026-01-06T16:00:00Z'),
      published: true,
      excerpt: 'Pakistan Stock Exchange closed the week with significant gains amid investor confidence.',
      content: 'By Business Desk, Karachi, The Pakistan Stock Exchange (PSX) ended the trading week on a positive note as the benchmark index gained over 700 points. Analysts linked the surge to improved macroeconomic indicators. Investors showed keen interest in banking, energy, and cement sectors. Market experts believe stability in the currency market also contributed to positive sentiment.',
    },
    {
      title: 'Punjab Launches Free Insulin Program',
      slug: 'punjab-free-insulin-program',
      category: 'Health',
      image: 'insulin-program.jpg',
      date: new Date('2026-01-09T09:20:00Z'),
      published: true,
      excerpt: 'The Punjab government has launched a free insulin distribution program for diabetic patients.',
      content: 'By our Correspondent, Lahore, The Punjab government has launched a free insulin program aimed at providing relief to low-income diabetic patients. The initiative will cover government hospitals across the province. Health officials said registered patients will receive monthly insulin supplies at no cost. Doctors welcomed the move, calling it a major step toward accessible healthcare.',
    },
    {
      title: 'Polio Vaccination Drive Begins Nationwide',
      slug: 'nationwide-polio-drive',
      category: 'Health',
      image: 'polio-drive.jpg',
      date: new Date('2026-01-08T08:00:00Z'),
      published: true,
      excerpt: 'A nationwide polio vaccination campaign has begun to immunize millions of children.',
      content: 'By Staff Reporter, Islamabad, Pakistan has launched a nationwide polio vaccination drive targeting children under the age of five. Health workers will administer drops in both urban and remote areas. Officials said strict security arrangements have been made to ensure the safety of vaccination teams. Parents have been urged to cooperate to help eradicate the virus.',
    },
    {
      title: 'New Burn Unit Inaugurated in Karachi',
      slug: 'burn-unit-karachi',
      category: 'Health',
      image: 'burn-unit.jpg',
      date: new Date('2026-01-07T13:40:00Z'),
      published: true,
      excerpt: 'A modern burn treatment unit has been inaugurated at a major hospital in Karachi.',
      content: 'By our Correspondent, Karachi, A state-of-the-art burn unit has been inaugurated at a government hospital in Karachi to improve emergency care services. The facility includes advanced operating theaters and isolation wards. Hospital administration said the unit will significantly reduce patient load on private hospitals. Medical staff have received specialized training for burn management.',
    },
    {
      title: 'KP Reports Decline in Dengue Cases',
      slug: 'kp-dengue-decline',
      category: 'Health',
      image: 'dengue-control.jpg',
      date: new Date('2026-01-06T10:10:00Z'),
      published: true,
      excerpt: 'Khyber Pakhtunkhwa has reported a decline in dengue cases due to effective preventive measures.',
      content: 'By Staff Reporter, Peshawar, Health authorities in Khyber Pakhtunkhwa have reported a significant decline in dengue cases compared to last year. Officials credited timely fumigation and awareness campaigns. Doctors advised the public to continue preventive practices, especially during seasonal changes. Surveillance teams remain active in high-risk areas.',
    },
    {
      title: 'Karachi Circular Railway Project Gains Momentum',
      slug: 'kcr-project-progress',
      category: 'Transport',
      image: 'kcr-project.jpg',
      date: new Date('2026-01-09T15:00:00Z'),
      published: true,
      excerpt: 'Work on the Karachi Circular Railway project has accelerated after funding approval.',
      content: 'By our Correspondent, Karachi, The Karachi Circular Railway (KCR) project has gained momentum following the release of development funds. Authorities confirmed that construction work is underway on multiple sections. Officials stated that the project will ease traffic congestion and provide affordable transport to commuters. The first phase is expected to be completed within a year.',
    },
    {
      title: 'New Electric Bus Service Launched in Islamabad',
      slug: 'electric-bus-islamabad',
      category: 'Transport',
      image: 'electric-bus.jpg',
      date: new Date('2026-01-08T12:15:00Z'),
      published: true,
      excerpt: 'Islamabad has launched a new electric bus service to promote eco-friendly transport.',
      content: 'By Staff Reporter, Islamabad, The federal capital has launched an electric bus service as part of efforts to reduce pollution and fuel costs. The buses will operate on major urban routes. Transport officials said the service will offer subsidized fares and modern facilities. Plans are underway to expand the fleet in the coming months.',
    },
    {
      title: 'Pakistan Railways Announces Fare Adjustment',
      slug: 'railway-fare-adjustment',
      category: 'Transport',
      image: 'pakistan-railways.jpg',
      date: new Date('2026-01-07T17:30:00Z'),
      published: true,
      excerpt: 'Pakistan Railways has announced a revision in passenger fares effective next week.',
      content: 'By our Correspondent, Lahore, Pakistan Railways has announced a modest increase in passenger fares due to rising operational costs. The revised fares will apply to all classes. Officials said the adjustment was unavoidable to maintain services and improve safety. Passenger associations have urged authorities to ensure better punctuality.',
    },
    {
      title: 'Motorway Extension Approved for Southern Punjab',
      slug: 'motorway-extension-south-punjab',
      category: 'Transport',
      image: 'motorway-extension.jpg',
      date: new Date('2026-01-06T11:50:00Z'),
      published: true,
      excerpt: 'The Government has approved a major motorway extension project in southern Punjab.',
      content: 'By Staff Reporter, Multan, The federal government has approved a new motorway extension connecting major cities in southern Punjab. The project aims to enhance regional connectivity and trade. Officials stated that construction will begin later this year. The motorway is expected to boost economic activity and reduce travel time.',
    },
    {
      title: 'Police Arrest Gang Involved in Street Crimes in Karachi',
      slug: 'karachi-street-crime-gang-arrested',
      category: 'Crime',
      image: 'police-arrest.jpg',
      date: new Date('2026-01-09T18:10:00Z'),
      published: true,
      excerpt: 'Karachi police have arrested members of a gang involved in multiple street crime incidents.',
      content: 'By our Correspondent, Karachi, Karachi police have arrested four members of a gang allegedly involved in street crimes across several neighborhoods of the city. The arrests were made during a late-night raid in the Korangi area. Police officials stated that the suspects were involved in mobile phone snatching and motorcycle theft. Weapons and stolen items were recovered from their possession, and further investigations are underway.',
    },
    {
      title: 'Jewelry Shop Robbery Foiled in Rawalpindi',
      slug: 'rawalpindi-jewelry-robbery-foiled',
      category: 'Crime',
      image: 'jewelry-shop.jpg',
      date: new Date('2026-01-08T16:40:00Z'),
      published: true,
      excerpt: 'A robbery attempt at a jewelry shop in Rawalpindi was foiled by timely police action.',
      content: 'By Staff Reporter, Rawalpindi, A robbery attempt at a jewelry shop in Rawalpindi was foiled after police responded swiftly to an emergency call. The suspects attempted to flee but were apprehended after a brief chase. Police officials said no casualties were reported during the incident. The suspects have been shifted to police custody for interrogation.',
    },
    {
      title: 'Suspected Drug Smuggler Arrested at Quetta Checkpoint',
      slug: 'drug-smuggler-arrested-quetta',
      category: 'Crime',
      image: 'drug-seizure.jpg',
      date: new Date('2026-01-07T12:25:00Z'),
      published: true,
      excerpt: 'Security forces arrested a suspected drug smuggler at a checkpoint near Quetta.',
      content: 'By our Correspondent, Quetta, Security forces arrested a suspected drug smuggler during a routine inspection at a checkpoint on the outskirts of Quetta. A large quantity of narcotics was recovered from the suspect’s vehicle. Officials said the suspect is believed to be part of an inter-provincial smuggling network. Authorities have launched an investigation to identify accomplices.',
    },
    {
      title: 'Rainfall Brings Relief from Cold Weather in Punjab',
      slug: 'punjab-rainfall-cold-relief',
      category: 'Weather',
      image: 'punjab-rain.jpg',
      date: new Date('2026-01-09T07:30:00Z'),
      published: true,
      excerpt: 'Light to moderate rainfall across Punjab has brought relief from dry cold conditions.',
      content: 'By Staff Reporter, Lahore, Light to moderate rainfall was recorded in several cities of Punjab, bringing relief from dry and chilly weather. Lahore, Gujranwala, and Faisalabad experienced intermittent showers. The Meteorological Department said the rain is expected to improve air quality. However, residents were advised to take precautions due to slippery roads.',
    },
    {
      title: 'Fog Disrupts Road Traffic in Punjab Plains',
      slug: 'fog-disrupts-traffic-punjab',
      category: 'Weather',
      image: 'dense-fog.jpg',
      date: new Date('2026-01-07T06:20:00Z'),
      published: true,
      excerpt: 'Dense fog has disrupted road traffic in several parts of Punjab.',
      content: 'By Staff Reporter, Lahore, Dense fog engulfed major highways and motorways across Punjab, leading to reduced visibility and traffic disruptions. Several routes were temporarily closed. Traffic police advised commuters to delay travel and use fog lights. Weather officials said foggy conditions may persist during early morning hours.',
    },
    {
      title: 'Karachi Experiences Mild Temperature Rise',
      slug: 'karachi-mild-temperature-rise',
      category: 'Weather',
      image: 'karachi-weather.jpg',
      date: new Date('2026-01-06T10:30:00Z'),
      published: true,
      excerpt: 'Karachi has experienced a slight rise in temperature over the past two days.',
      content: 'By our Correspondent, Karachi, Karachi recorded a mild increase in temperature, with daytime readings slightly above seasonal average. Weather experts attributed the change to shifting wind patterns. The Meteorological Department said no heatwave is expected. Sea breezes are likely to regulate temperatures in coming days.',
    },
    {
      title: 'Rangers Conduct Security Operation in Karachi',
      slug: 'rangers-security-operation-karachi',
      category: 'Law and Order',
      image: 'rangers-operation.jpg',
      date: new Date('2026-01-09T20:00:00Z'),
      published: true,
      excerpt: 'Pakistan Rangers conducted a targeted security operation in Karachi.',
      content: 'By Staff Reporter, Karachi, Pakistan Rangers conducted a targeted security operation in parts of Karachi to curb criminal activities. Several suspects were detained for questioning. Officials said the operation was based on intelligence reports. Law enforcement agencies reiterated their commitment to maintaining peace in the city.',
    },
    {
      title: 'Section 144 Imposed Ahead of Major Procession',
      slug: 'section-144-procession',
      category: 'Law and Order',
      image: 'section-144.jpg',
      date: new Date('2026-01-08T19:15:00Z'),
      published: true,
      excerpt: 'Authorities have imposed Section 144 in parts of the city ahead of a major religious procession.',
      content: 'By Staff Reporter, Lahore, The district administration has imposed Section 144 in sensitive areas ahead of an upcoming religious procession. The decision aims to prevent any untoward incidents. Officials said security personnel will be deployed along procession routes. Citizens have been urged to cooperate with law enforcement agencies.',
    },
    {
      title: 'Anti-Encroachment Drive Launched in Multan',
      slug: 'multan-anti-encroachment-drive',
      category: 'Law and Order',
      image: 'encroachment-drive.jpg',
      date: new Date('2026-01-06T15:40:00Z'),
      published: true,
      excerpt: 'Multan administration has launched an anti-encroachment drive in busy markets.',
      content: 'By our Correspondent, Multan, The district administration in Multan has launched an anti-encroachment drive to clear illegal structures from roads and footpaths. Heavy machinery was used during the operation. Officials said the drive aims to ease traffic flow and improve public convenience. Shopkeepers were warned against re-establishing encroachments.',
    },
    {
      title: 'Lahore Hosts Annual Cultural Festival',
      slug: 'lahore-annual-cultural-festival',
      category: 'Culture',
      image: 'lahore-cultural-festival.jpg',
      date: new Date('2026-01-09T17:00:00Z'),
      published: true,
      excerpt: 'Lahore hosted its annual cultural festival showcasing traditional music, crafts, and cuisine.',
      content: 'By our Correspondent, Lahore, The annual cultural festival in Lahore began on Friday, attracting large crowds from across the city. The event features traditional music performances, folk dances, and exhibitions of handicrafts from different regions of Pakistan. Organizers said the festival aims to promote cultural heritage and provide a platform for local artists. Families and tourists were seen enjoying regional food stalls and live performances.',
    },
    {
      title: 'Pakistan National Museum Hosts Heritage Exhibition',
      slug: 'national-museum-heritage-exhibition',
      category: 'Culture',
      image: 'heritage-exhibition.jpg',
      date: new Date('2026-01-07T15:10:00Z'),
      published: true,
      excerpt: 'A heritage exhibition has opened at the Pakistan National Museum in Karachi.',
      content: 'By our Correspondent, Karachi, The Pakistan National Museum has inaugurated a heritage exhibition displaying artifacts from the Indus Valley Civilization and Islamic periods. The exhibition aims to educate the public about the country’s rich history. Museum officials said the display will remain open for a month. Students and history enthusiasts showed keen interest on the opening day.',
    },
    {
      title: 'Tree Plantation Drive Launched in Islamabad',
      slug: 'islamabad-tree-plantation-drive',
      category: 'Environment',
      image: 'tree-plantation.jpg',
      date: new Date('2026-01-09T08:40:00Z'),
      published: true,
      excerpt: 'A large-scale tree plantation drive has been launched in Islamabad.',
      content: 'By Staff Reporter, Islamabad, The Capital Development Authority has launched a tree plantation drive in Islamabad as part of efforts to increase green cover. Thousands of saplings will be planted in parks and along major roads. Officials said the initiative aims to improve air quality and combat climate change. Citizens and students have been encouraged to participate in the drive.',
    },
    {
      title: 'Smog Levels Decline in Lahore After Rainfall',
      slug: 'lahore-smog-levels-decline',
      category: 'Environment',
      image: 'lahore-smog.jpg',
      date: new Date('2026-01-08T09:10:00Z'),
      published: true,
      excerpt: 'Lahore has witnessed a decline in smog levels following recent rainfall.',
      content: 'By our Correspondent, Lahore, Environmental monitoring agencies reported a noticeable decline in smog levels across Lahore after recent rainfall. Air quality index readings showed improvement in several areas. Experts warned that the relief may be temporary and stressed the need for long-term measures. Authorities reiterated calls to control vehicular emissions and industrial pollution.',
    },
    {
      title: 'Sindh Government Announces Coastal Protection Plan',
      slug: 'sindh-coastal-protection-plan',
      category: 'Environment',
      image: 'coastal-protection.jpg',
      date: new Date('2026-01-07T14:50:00Z'),
      published: true,
      excerpt: 'Sindh government has announced a new plan to protect coastal areas from erosion.',
      content: 'By Staff Reporter, Karachi, The Sindh government has announced a comprehensive coastal protection plan to address sea erosion and rising sea levels. The initiative focuses on mangrove restoration and infrastructure strengthening. Environmental experts welcomed the plan, stating it would help protect coastal communities. Implementation is expected to begin later this year.',
    }
  ];

  console.log(`--- Seeding ${newsData.length} new posts ---`);
  
  // createMany is efficient for bulk insertion
  await prisma.post.createMany({
    data: newsData,
  });

  console.log('--- Seeding completed successfully ---');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });